server:
  error:
    include-message: always
    include-binding-errors: always
  address: localhost
  port: 8080

spring:
  datasource:
    password: g1379852
    url: jdbc:mysql://localhost:3306/slabel?serverTimezone=Asia/Seoul
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
